apiVersion: v1
kind: Pod
metadata:
  name: node-restful-api-postgres
  labels:
    name: node-restful-api-postgres
spec:
  containers:
  - name: node-restful-api-postgres
    image: postgres:12-alpine
    env:
      - name: POSTGRES_PASSWORD
        value: postgres
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_DB
        value: restful-api
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5432
---

apiVersion: v1
kind: Service
metadata:
  name: node-restful-api-postgres-service
spec:
  selector:
    name: node-restful-api-postgres
  ports:
  - port: 5432
    targetPort: 5432
---

apiVersion: v1
kind: Pod
metadata:
  name: node-restful-api
  labels:
    name: node-restful-api
spec:
  containers:
  - name: node-restful-api
    image: node-restful-api
    env:
      - name: DATABASE_HOST
        value: node-restful-api-postgres
      - name: DATABASE_PORT
        value: "5432"
      - name: DATABASE_USER
        value: postgres
      - name: DATABASE_PASSWORD
        value: postgres
      - name: DATABASE_NAME
        value: restful-api
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: node-restful-api
spec:
  selector:
    name: node-restful-api
  ports:
  - port: 8080
    targetPort: 8080
